{{- if .Values.gubernator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gubernator.serviceAccount.name }}
  labels:
  {{- include "gubernator.labels" . | nindent 4 }}
  annotations:
  {{- include "gubernator.annotations" . | nindent 4 }}
{{- end }}
