gubernator:

  fullnameOverride: {}
  nameOverride: {}
  priorityClassName: {}

  autoscaling:
    enabled: false

  replicaCount: 4

  image:
    repository: thrawn01/gubernator
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

#  labels:
#    a: "b"

#  debug: true
#  watchPods: true

  server:
    http:
      port: "80"
    grpc:
      port: "81"
#      maxConnAgeSeconds: 30

  annotations: { }

  serviceAccount:
    create: true
#    name: "teste"

  nodeSelector:
    group: apps

  resources:
    requests:
      cpu: 100m
      memory: 150Mi